export const COMMON_ERRORS = {
  UNEXPECTED: 'COMMON.UNEXPECTED_ERROR',
  VALIDATION: 'COMMON.VALIDATION_ERROR',
  DUPLICATE_RESOURCE: 'COMMON.DUPLICATE_RESOURCE',
  RESOURCE_NOT_FOUND: 'COMMON.RESOURCE_NOT_FOUND',
  INVALID_RELATION: 'COMMON.INVALID_RELATION',
} as const;

export type CommonErrorCode =
  (typeof COMMON_ERRORS)[keyof typeof COMMON_ERRORS];
